# Generated by Django 2.2.5 on 2020-04-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_name', models.CharField(max_length=45)),
                ('de_college', models.CharField(max_length=45, null=True)),
                ('de_info', models.CharField(max_length=300, null=True)),
                ('de_instructor', models.CharField(max_length=45, null=True)),
                ('de_picture', models.CharField(default='', max_length=300)),
                ('de_address', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DutyBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=25)),
                ('end_time', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=45)),
                ('num_people', models.IntegerField()),
                ('duty_batch', models.ForeignKey(on_delete='CASCADE', to='index.DutyBatch')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftsStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifts', models.ForeignKey(on_delete='CASCADE', to='index.Shifts')),
            ],
        ),
        migrations.CreateModel(
            name='StationBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('start_time', models.DateTimeField()),
                ('content', models.TextField(null=True)),
                ('limit_num', models.IntegerField(default=2)),
                ('page_views', models.IntegerField()),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=15)),
                ('user_level', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=45)),
                ('user_sex', models.CharField(max_length=15)),
                ('user_specialty', models.CharField(max_length=45, null=True)),
                ('user_college', models.CharField(max_length=45, null=True)),
                ('user_qq', models.CharField(max_length=12, null=True)),
                ('user_organization', models.CharField(max_length=45, null=True)),
                ('user_hobby', models.CharField(max_length=45, null=True)),
                ('user_autograph', models.CharField(max_length=125, null=True)),
                ('user_instructor', models.CharField(max_length=45, null=True)),
                ('user_picture', models.CharField(max_length=300, null=True)),
                ('state', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete='CASCADE', to='index.Department')),
                ('user_phone', models.OneToOneField(null=True, on_delete='CASCADE', to='index.User')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFreeTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_time', models.CharField(max_length=45, null=True)),
                ('state', models.IntegerField()),
                ('student', models.OneToOneField(on_delete='CASCADE', to='index.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('duty', models.TextField()),
                ('num_recruit', models.IntegerField()),
                ('department', models.ForeignKey(on_delete='CASCADE', to='index.Department')),
                ('station_batch', models.ForeignKey(on_delete='CASCADE', to='index.StationBatch')),
            ],
        ),
        migrations.CreateModel(
            name='SignDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_in_time', models.DateTimeField()),
                ('sign_off_time', models.DateTimeField()),
                ('late', models.TimeField()),
                ('sign_state', models.IntegerField(default=0)),
                ('evaluate', models.IntegerField()),
                ('shifts_student', models.ForeignKey(on_delete='CASCADE', to='index.ShiftsStudent')),
            ],
        ),
        migrations.AddField(
            model_name='shiftsstudent',
            name='student',
            field=models.ForeignKey(on_delete='CASCADE', to='index.UserInfo'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_type', models.CharField(max_length=15)),
                ('theme', models.CharField(max_length=45)),
                ('re_file', models.CharField(max_length=300)),
                ('re_content', models.TextField()),
                ('upload_time', models.DateTimeField()),
                ('num_download', models.IntegerField()),
                ('remark', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(on_delete='CASCADE', to='index.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='dutybatch',
            name='admin',
            field=models.ForeignKey(on_delete='CASCADE', to='index.UserInfo'),
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('bu_file', models.CharField(max_length=300)),
                ('bu_content', models.TextField()),
                ('release_time', models.DateTimeField()),
                ('num_views', models.IntegerField()),
                ('remark', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(on_delete='CASCADE', to='index.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('image', models.CharField(max_length=300)),
                ('political_status', models.CharField(max_length=45)),
                ('sc_address', models.CharField(max_length=120)),
                ('ho_address', models.CharField(max_length=120)),
                ('wechat', models.CharField(max_length=30)),
                ('postal_code', models.IntegerField()),
                ('bank_card', models.BigIntegerField()),
                ('degree_of_difficulty', models.IntegerField()),
                ('transfer', models.IntegerField(default=1)),
                ('go_other', models.IntegerField(default=0)),
                ('other_department', models.CharField(max_length=45, null=True)),
                ('fail_exam', models.IntegerField(default=0)),
                ('performance', models.TextField()),
                ('apply_reason', models.TextField()),
                ('lesson_code', models.CharField(max_length=45)),
                ('student', models.OneToOneField(on_delete='CASCADE', to='index.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.ForeignKey(on_delete='CASCADE', to='index.Station')),
                ('student', models.ForeignKey(on_delete='CASCADE', to='index.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='AchievementsBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('check', models.IntegerField(null=True)),
                ('wage', models.FloatField()),
                ('overtime_wage', models.FloatField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('compute_method', models.IntegerField(default=1)),
                ('ach_state', models.IntegerField()),
                ('remark', models.CharField(max_length=300)),
                ('admin', models.ForeignKey(on_delete='CASCADE', to='index.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_hour', models.FloatField()),
                ('overtime_hour', models.FloatField()),
                ('money', models.FloatField()),
                ('check', models.IntegerField(default=1)),
                ('achievementsbatch', models.ForeignKey(on_delete='CASCADE', to='index.AchievementsBatch')),
            ],
        ),
    ]
