# Generated by Django 2.2.5 on 2020-04-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200411_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='index.Department'),
        ),
    ]
