# Generated by Django 2.2.5 on 2020-04-11 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200411_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
    ]
