# Generated by Django 2.2.5 on 2020-04-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200411_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTimeTableInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=155)),
                ('state', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentfreetime',
            name='state',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentfreetime',
            name='student',
            field=models.ForeignKey(on_delete='CASCADE', to='index.UserInfo'),
        ),
        migrations.AddField(
            model_name='studentfreetime',
            name='table_info',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='index.FreeTimeTableInfo'),
        ),
    ]
