# Generated by Django 2.2.5 on 2020-04-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200412_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfreetime',
            name='table_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.FreeTimeTableInfo'),
        ),
    ]
